/**
 * Payment Receipt Generation
 * 
 * PDF receipt generation utilities
 */

const functions = require("firebase-functions");
const admin = require("firebase-admin");
const { requireAuth } = require("../guards/authGuard");
const { requireOwnership } = require("../guards/ownershipGuard");

/**
 * Generate PDF receipt using pdf-lib
 */
async function generateReceiptPDF(data) {
  const { PDFDocument, rgb } = require('pdf-lib');

  // Create a new PDF document
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage();
  const { width, height } = page.getSize();

  // Set up fonts and colors
  const fontSize = 12;
  const titleFontSize = 18;
  const blueColor = rgb(0.1, 0.4, 0.8);
  const grayColor = rgb(0.5, 0.5, 0.5);

  // Helper function to draw text
  let yPosition = height - 50;

  function drawText(text, x = 50, size = fontSize, color = rgb(0, 0, 0)) {
    page.drawText(text, { x, y: yPosition, size, color });
    yPosition -= size + 5;
  }

  function drawTitle(text) {
    drawText(text, 50, titleFontSize, blueColor);
    yPosition -= 10;
  }

  function drawSection(text) {
    drawText(text, 50, 14, blueColor);
    yPosition -= 5;
  }

  // Header
  drawTitle('💰 Payment Receipt');
  drawText(`Transaction ID: ${data.transaction.id}`, 50, 10, grayColor);
  drawText(`Date: ${new Date(data.transaction.processedAt?.toDate?.() || data.transaction.processedAt).toLocaleDateString('en-IN')}`, 50, 10, grayColor);
  yPosition -= 20;

  // Partner Information
  drawSection('Partner Information');
  drawText(`Name: ${data.partner?.personalDetails?.fullName || data.partner?.fullName || 'N/A'}`);
  drawText(`Partner ID: ${data.partner?.id}`);
  drawText(`Mobile: ${data.partner?.personalDetails?.mobileNo || data.partner?.mobileNo || 'N/A'}`);
  yPosition -= 15;

  // Payment Details
  drawSection('Payment Details');
  drawText(`Amount Paid: ₹${data.transaction.amount?.toLocaleString('en-IN') || '0'}`);
  drawText(`Payment Method: ${data.transaction.paymentMethod || 'Bank Transfer'}`);
  drawText(`Transaction Status: ${data.transaction.status || 'Completed'}`);
  drawText(`Processing Fees: ₹${data.transaction.fees?.toLocaleString('en-IN') || '0'}`);

  if (data.transaction.transactionRef) {
    drawText(`Reference Number: ${data.transaction.transactionRef}`);
  }
  yPosition -= 15;

  // Bank Account Details
  if (data.bankAccount) {
    drawSection('Bank Account Details');
    drawText(`Account Holder: ${data.bankAccount.accountHolderName}`);
    drawText(`Bank Name: ${data.bankAccount.bankName}`);
    drawText(`Account Number: ****${data.bankAccount.accountNumber?.slice(-4) || '****'}`);
    drawText(`IFSC Code: ${data.bankAccount.ifscCode}`);
  }
  yPosition -= 15;

  // Settlement Information
  if (data.payoutRequest) {
    drawSection('Settlement Information');
    drawText(`Settlement Period: ${data.payoutRequest.settlementId || 'N/A'}`);
    drawText(`Requested Amount: ₹${data.payoutRequest.requestedAmount?.toLocaleString('en-IN') || '0'}`);
    drawText(`Request Date: ${new Date(data.payoutRequest.requestedAt?.toDate?.() || data.payoutRequest.requestedAt).toLocaleDateString('en-IN')}`);

    if (data.payoutRequest.processedAt) {
      drawText(`Processed Date: ${new Date(data.payoutRequest.processedAt?.toDate?.() || data.payoutRequest.processedAt).toLocaleDateString('en-IN')}`);
    }
  }
  yPosition -= 30;

  // Footer
  drawText('Thank you for your service!', 50, 10, grayColor);
  drawText('Generated by Serveit Partner App', 50, 8, grayColor);
  drawText(`Generated on: ${new Date().toLocaleString('en-IN')}`, 50, 8, grayColor);

  // Add border
  page.drawRectangle({
    x: 20,
    y: 20,
    width: width - 40,
    height: height - 40,
    borderColor: grayColor,
    borderWidth: 1
  });

  // Serialize the PDF
  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}

/**
 * Generate Payment Receipt
 * 
 * HTTPS Callable function to generate and download payment receipts
 */
function createGeneratePaymentReceiptFunction(db, collections) {
  return functions.https.onCall(async (data, context) => {
    requireAuth(context);

    const { transactionId } = data;

    if (!transactionId) {
      throw new functions.https.HttpsError('invalid-argument', 'transactionId is required');
    }

    try {
      // Get transaction details
      const transactionDoc = await db.collection(collections.payoutTransactions).doc(transactionId).get();
      if (!transactionDoc.exists) {
        throw new functions.https.HttpsError('not-found', 'Transaction not found');
      }

      const transactionData = transactionDoc.data();

      // Verify ownership (user can only access their own transactions)
      requireOwnership(transactionData.partnerId, context.auth.uid, 'transaction');

      // Get related data
      const [payoutRequestDoc, bankAccountDoc, partnerDoc] = await Promise.all([
        transactionData.payoutRequestId ? db.collection(collections.payoutRequests).doc(transactionData.payoutRequestId).get() : Promise.resolve(null),
        transactionData.bankAccountId ? db.collection(collections.bankAccounts).doc(transactionData.bankAccountId).get() : Promise.resolve(null),
        db.collection(collections.partners).doc(transactionData.partnerId).get()
      ]);

      const payoutRequest = payoutRequestDoc?.exists ? payoutRequestDoc.data() : null;
      const bankAccount = bankAccountDoc?.exists ? bankAccountDoc.data() : null;
      const partner = partnerDoc?.exists ? partnerDoc.data() : null;

      // Generate PDF receipt
      const pdfBuffer = await generateReceiptPDF({
        transaction: { id: transactionDoc.id, ...transactionData },
        payoutRequest: payoutRequest ? { id: payoutRequestDoc.id, ...payoutRequest } : null,
        bankAccount: bankAccount ? { id: bankAccountDoc.id, ...bankAccount } : null,
        partner: partner ? { id: partnerDoc.id, ...partner } : null
      });

      // Upload to Cloud Storage
      const bucket = admin.storage().bucket();
      const fileName = `receipts/${transactionData.partnerId}/${transactionId}.pdf`;
      const file = bucket.file(fileName);

      await file.save(pdfBuffer, {
        metadata: {
          contentType: 'application/pdf',
          metadata: {
            transactionId: transactionId,
            partnerId: transactionData.partnerId,
            amount: transactionData.amount.toString(),
            generatedAt: new Date().toISOString()
          }
        }
      });

      // Make file publicly accessible for download
      await file.makePublic();

      // Get download URL
      const [url] = await file.getSignedUrl({
        action: 'read',
        expires: Date.now() + (365 * 24 * 60 * 60 * 1000) // 1 year
      });

      // Update transaction with receipt URL
      await db.collection(collections.payoutTransactions).doc(transactionId).update({
        receiptUrl: url,
        receiptGeneratedAt: admin.firestore.FieldValue.serverTimestamp()
      });

      return {
        success: true,
        receiptUrl: url,
        fileName: `${transactionId}.pdf`
      };

    } catch (error) {
      console.error('Error generating receipt:', error);
      if (error instanceof functions.https.HttpsError) {
        throw error;
      }
      throw new functions.https.HttpsError('internal', 'Failed to generate receipt');
    }
  });
}

module.exports = {
  createGeneratePaymentReceiptFunction,
  generateReceiptPDF
};

